"""Regenerate device_names.py from AppleDB.

Apple's version feed publishes only model identifiers ("iPhone14,4"), never
marketing names, so the names have to come from somewhere else. AppleDB
(https://github.com/littlebyteorg/appledb, MIT licensed) maintains an
identifier -> name mapping.

Usage:
    git clone --depth 1 https://github.com/littlebyteorg/appledb /tmp/appledb
    python3 scripts/generate_device_names.py /tmp/appledb
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

# Families Apple's version feed actually publishes. Anything else (PowerPC
# Macs, AirPort base stations, Beats headphones) only bloats the table.
FAMILIES = {
    "ADP",
    "AppleTV",
    "AudioAccessory",
    "iMac",
    "iMacPro",
    "iPad",
    "iPhone",
    "iPod",
    "Mac",
    "MacBook",
    "MacBookAir",
    "MacBookPro",
    "Macmini",
    "MacPro",
    "RealityDevice",
    "VirtualMac",
    "Watch",
}

# AppleDB files these two only under a qualifier that is not true of the
# device generally, so the plain product name is used instead. The identifier
# is shown next to the name in the picker either way.
OVERRIDES = {
    "AudioAccessory1,2": "HomePod (1st generation)",
    "AudioAccessory5,1": "HomePod mini",
}

IDENTIFIER = re.compile(r"^([A-Za-z]+)(\d+),(\d+)$")

OUTPUT = (
    pathlib.Path(__file__).parent.parent
    / "custom_components"
    / "apple_device_latest_version"
    / "device_names.py"
)

HEADER = '''"""Marketing names for Apple model identifiers.

Generated by scripts/generate_device_names.py -- do not edit by hand.

Apple's version feed publishes only identifiers like "iPhone14,4", so these
names come from AppleDB (https://github.com/littlebyteorg/appledb), which is
MIT licensed. An identifier missing from this table falls back to being shown
as-is, so a brand new device is still selectable.
"""

from __future__ import annotations

DEVICE_NAMES: dict[str, str] = {
'''


def main(appledb: str) -> int:
    root = pathlib.Path(appledb) / "deviceFiles"
    if not root.is_dir():
        print(f"no deviceFiles directory under {appledb}", file=sys.stderr)
        return 1

    candidates: dict[str, set[str]] = {}
    for path in root.rglob("*.json"):
        try:
            loaded = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        for entry in loaded if isinstance(loaded, list) else [loaded]:
            if not isinstance(entry, dict):
                continue
            identifier, name = entry.get("identifier"), entry.get("name")
            if not isinstance(identifier, str) or not isinstance(name, str):
                continue
            match = IDENTIFIER.match(identifier)
            if not match or match.group(1) not in FAMILIES:
                continue
            candidates.setdefault(identifier, set()).add(name.strip())

    # Some identifiers cover several variants (a rack Mac Pro, two model
    # years). Pick the shortest name, which is the base model, then break ties
    # alphabetically so regenerating never reshuffles the table.
    names = {
        identifier: sorted(variants, key=lambda n: (len(n), n))[0]
        for identifier, variants in candidates.items()
    }
    names.update(
        {
            identifier: name
            for identifier, name in OVERRIDES.items()
            if identifier in names
        }
    )

    def sort_key(identifier: str) -> tuple[str, int, int]:
        match = IDENTIFIER.match(identifier)
        assert match
        return (match.group(1), int(match.group(2)), int(match.group(3)))

    lines = [HEADER]
    lines += [
        f'    "{identifier}": {json.dumps(names[identifier])},\n'
        for identifier in sorted(names, key=sort_key)
    ]
    lines.append("}\n")
    OUTPUT.write_text("".join(lines))

    print(f"wrote {OUTPUT} with {len(names)} identifiers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/appledb"))
